# config.yaml
apprise: # 'apprise' is the name of the service used for notifications https://github.com/caronc/apprise
  enabled: true  # set it to false to disable apprise globally, can be overridden with command-line arguments.
  notify:
    incomplete-activity: true # set it to false to disable notifications for incomplete activities
    uncaught-exception: true # set it to false to disable notifications for uncaught exceptions
    login-code: true # set it to false to disable notifications for the temporary M$ Authenticator login code
  summary: ALWAYS # set it to ALWAYS to always receive a summary about your points progression or errors, or to 
    # NEVER to never receive a summary, even in case of an error. 
  urls: # add apprise urls here to receive notifications on the specified services :
    # https://github.com/caronc/apprise#supported-notifications
    # Empty by default.
    - discord://{WebhookID}/{WebhookToken} # Exemple url 
browser:
  geolocation: US # Replace with your country code https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2.
    # Can be overridden with command-line arguments.
  language: en # Replace with your language code https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes.
    # Can be overridden with command-line arguments.
  visible: true # set it to true to show the browser window, can be overridden with command-line arguments.
  proxy: null # set the global proxy using the 'http://user:pass@host:port' syntax.
    # Override per-account proxies. Can be overridden with command-line arguments.
activities:
  ignore: # list of activities to ignore, like activities that can't be completed
    - Get 50 entries plus 1000 points!
    - Safeguard your family's info
    - Get Spotify Premium for free
    - A new web hero
  search: # list of searches to do for search-based activities
    "Black Friday shopping": black friday deals
    "Discover open job roles": jobs at microsoft
    "Expand your vocabulary": define demure
    "Find places to stay": hotels rome italy
    "Find somewhere new to explore": directions to new york
    "Gaming time": vampire survivors video game
    "Get your shopping done faster": new iphone
    "Houses near you": apartments manhattan
    "How's the economy?": sp 500
    "Learn to cook a new recipe": how cook pierogi
    "Let's watch that movie again!": aliens movie
    "Plan a quick getaway": flights nyc to paris
    "Prepare for the weather": weather tomorrow
    "Quickly convert your money": convert 374 usd to yen
    "Search the lyrics of a song": black sabbath supernaut lyrics
    "Stay on top of the elections": election news latest
    "Too tired to cook tonight?": Pizza Hut near me
    "Translate anything": translate pencil sharpener to spanish
    "What time is it?": china time
    "What's for Thanksgiving dinner?": pumpkin pie recipe
    "Who won?": braves score
    "You can track your package": usps tracking
logging:
  level: INFO # Set to DEBUG, WARNING, ERROR or CRITICAL to change the level of displayed information in the terminal
    # See https://docs.python.org/3/library/logging.html#logging-levels. Can be overridden with command-line arguments.
retries:
  base_delay_in_seconds: 120 # The base wait time between each retries. Multiplied by two each try.
  max: 4 # The maximal number of retries to do
  strategy: EXPONENTIAL # Set it to CONSTANT to use the same delay between each retries.
    # Else, increase it exponentially each time.
cooldown:
  min: 300 # The minimal wait time between two searches/activities
  max: 600 # The maximal wait time between two searches/activities
search:
  type: both # Set it to 'mobile' or 'desktop' to only complete searches on one plateform,
    # can be overridden with command-line arguments.
accounts: # The accounts to use. You can put zero, one or an infinite number of accounts here.
    # Empty by default, can be overridden with command-line arguments.
  - email: Your Email 1 # replace with your email
    password: Your Password 1 # replace with your password
  - email: Your Email 2 # replace with your email
    password: Your Password 2 # replace with your password